import asyncio
from dataclasses import asdict
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

import chainlit as cl
import pytest
from pydantic_ai.models.test import TestModel

from .utils import init_chainlit_context


@pytest.mark.asyncio
async def test_scheduling(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    users_dir = tmp_path / "users"
    users_dir.mkdir()

    monkeypatch.setenv("MODEL", "test")

    from agent_penny import agent, user_data

    monkeypatch.setattr(user_data, "data_dir", tmp_path)
    monkeypatch.setattr(user_data, "users_dir", users_dir)

    monkeypatch.setattr(
        agent,
        "default_model",
        TestModel(custom_output_text="You did it!", call_tools=[]),
    )
    monkeypatch.setattr(agent, "default_thinking", False)

    import app  # noqa: F401
    from agent_penny.capabilities import scheduling
    from agent_penny.capabilities.scheduling import ScheduledJob
    from agent_penny.chainlit_utils import get_user

    await init_chainlit_context()

    user = get_user()

    # HACK: Scheduling relies on user information normally generated by the data-layer
    user_data.save(
        "user.json",
        cl.PersistedUser(
            id=user.identifier, createdAt=datetime.now().isoformat(), **asdict(user)
        ).to_json(),
    )

    scheduling.startup()

    scheduling.SchedulingCapability()

    timezone = "America/Vancouver"

    scheduling.upsert_job(
        ScheduledJob(
            name="test-job",
            prompt="test prompt",
            date=datetime.now(tz=ZoneInfo(timezone)),
            timezone=timezone,
        )
    )

    await asyncio.sleep(1)

    if scheduling._threads:
        await asyncio.gather(*(asyncio.to_thread(t.join) for t in scheduling._threads))

    job: scheduling.ScheduledJob = scheduling.load_job("test-job")

    assert job.last_execution is not None
    assert job.last_execution.status == "finished"
    assert job.last_execution.result == "You did it!"
